# [Link](linktr.ee/taahahussainkhan)

# Question 01

In [1]:
import numpy as np

# Part a

In [4]:
random_arr = np.random.rand(5,5) # 5x5 matrix with random values
random_arr

array([[0.66048391, 0.59045745, 0.81150763, 0.18669637, 0.21447567],
       [0.33729468, 0.56129881, 0.91677196, 0.69832661, 0.36270168],
       [0.35417495, 0.19493396, 0.76064317, 0.4280939 , 0.44132356],
       [0.10064613, 0.28919264, 0.34386042, 0.66699611, 0.81637435],
       [0.1381993 , 0.22019819, 0.35343938, 0.79615432, 0.18663647]])

In [9]:
flatt_arr = random_arr.flatten()
sorted_arr = np.sort(flatt_arr,axis=0) # axis=0: sort by column, axis=1: sort by row
sorted_arr

array([0.10064613, 0.1381993 , 0.18663647, 0.18669637, 0.19493396,
       0.21447567, 0.22019819, 0.28919264, 0.33729468, 0.34386042,
       0.35343938, 0.35417495, 0.36270168, 0.4280939 , 0.44132356,
       0.56129881, 0.59045745, 0.66048391, 0.66699611, 0.69832661,
       0.76064317, 0.79615432, 0.81150763, 0.81637435, 0.91677196])

In [12]:
second_min = sorted_arr[1] # 2nd minimum
print(f'Second Minimum is: {second_min}')
max_num = sorted_arr[-1] # Maximum
print(f'Maximum is: {max_num}')

Second Minimum is: 0.13819930403160785
Maximum is: 0.9167719564042718


# Part b

In [19]:
normalized_arr = (random_arr - second_min)/(max_num - second_min) # Normalization

In [25]:
print(f'Normalized array: {normalized_arr}')

Normalized array: [[ 0.67082321  0.58088111  0.86479833  0.06228971  0.09796949]
 [ 0.25571843  0.54342971  1.          0.71942843  0.28835122]
 [ 0.27739947  0.07287008  0.79946793  0.37234109  0.3893333 ]
 [-0.04823335  0.19393609  0.26415148  0.67918749  0.87104915]
 [ 0.40977031  0.1053195   0.2764547   0.84507851  0.06221277]]


In [26]:
normalized_arr[normalized_arr == 0] = np.mean(normalized_arr) # Replace 0 with mean
print(f'Array after replacing 0 with mean: {normalized_arr}')

Array after replacing 0 with mean: [[ 0.67082321  0.58088111  0.86479833  0.06228971  0.09796949]
 [ 0.25571843  0.54342971  1.          0.71942843  0.28835122]
 [ 0.27739947  0.07287008  0.79946793  0.37234109  0.3893333 ]
 [-0.04823335  0.19393609  0.26415148  0.67918749  0.87104915]
 [ 0.40977031  0.1053195   0.2764547   0.84507851  0.06221277]]


# [Link](linktr.ee/taahahussainkhan)