# Question 2

In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
temperature = np.random.randint(30,45,size=(12,30))
temperature

array([[38, 44, 40, 35, 34, 34, 37, 34, 43, 35, 35, 35, 36, 35, 39, 35,
        34, 38, 39, 31, 35, 34, 35, 35, 39, 30, 39, 40, 37, 30],
       [31, 35, 39, 40, 36, 40, 31, 36, 41, 31, 36, 38, 40, 43, 33, 43,
        32, 40, 32, 38, 39, 37, 36, 41, 43, 34, 35, 35, 37, 32],
       [31, 39, 35, 33, 32, 30, 37, 36, 35, 36, 43, 38, 34, 30, 43, 33,
        40, 37, 41, 42, 32, 43, 36, 33, 37, 30, 31, 40, 40, 39],
       [34, 39, 32, 30, 36, 43, 44, 31, 35, 32, 35, 31, 31, 36, 33, 36,
        41, 31, 43, 31, 30, 43, 35, 43, 43, 35, 40, 32, 44, 36],
       [40, 39, 31, 33, 43, 31, 37, 31, 41, 33, 36, 32, 41, 37, 41, 32,
        33, 40, 32, 34, 33, 37, 41, 37, 35, 34, 34, 30, 37, 33],
       [40, 42, 39, 32, 31, 32, 30, 41, 36, 40, 38, 34, 35, 36, 44, 31,
        40, 31, 38, 33, 32, 43, 35, 37, 30, 38, 32, 37, 31, 44],
       [31, 31, 41, 36, 42, 44, 36, 37, 40, 42, 40, 40, 34, 36, 39, 39,
        37, 41, 36, 30, 40, 37, 36, 43, 31, 32, 44, 31, 41, 38],
       [39, 35, 44, 40, 42, 40, 38, 42, 3

In [19]:
temp_avg = np.round(np.mean(temperature,axis=1),2)
temp_avg

array([36.17, 36.8 , 36.2 , 36.17, 35.6 , 36.07, 37.5 , 37.3 , 36.53,
       37.97, 37.97, 37.57])

In [20]:
humidity = np.random.randint(40,60,size=(12,30))
humidity

array([[58, 40, 52, 50, 58, 43, 47, 46, 54, 50, 55, 45, 50, 47, 44, 47,
        40, 51, 56, 51, 54, 59, 49, 40, 56, 57, 40, 52, 47, 43],
       [56, 57, 48, 44, 54, 44, 51, 58, 59, 51, 50, 41, 58, 43, 55, 49,
        42, 51, 42, 51, 53, 48, 57, 42, 40, 59, 55, 48, 57, 42],
       [47, 43, 53, 51, 42, 43, 50, 47, 52, 41, 50, 46, 48, 45, 59, 40,
        46, 47, 54, 41, 44, 56, 59, 54, 55, 47, 49, 53, 45, 57],
       [46, 58, 40, 51, 57, 47, 40, 55, 49, 55, 42, 49, 46, 56, 44, 50,
        52, 59, 52, 47, 59, 52, 40, 46, 42, 59, 49, 53, 46, 57],
       [42, 58, 49, 44, 52, 58, 59, 53, 53, 58, 47, 41, 59, 54, 40, 51,
        40, 57, 58, 53, 58, 50, 42, 47, 52, 52, 55, 46, 42, 51],
       [47, 53, 58, 41, 57, 40, 55, 50, 46, 40, 56, 42, 57, 57, 52, 46,
        58, 50, 50, 59, 43, 58, 59, 40, 50, 46, 47, 40, 55, 41],
       [53, 59, 48, 54, 47, 59, 52, 51, 53, 47, 44, 57, 52, 50, 59, 51,
        54, 46, 46, 41, 54, 49, 47, 57, 48, 54, 56, 43, 58, 56],
       [41, 54, 48, 44, 41, 53, 43, 41, 4

In [21]:
hum_avg = np.round(np.mean(humidity,axis=1),2)
hum_avg

array([49.37, 50.17, 48.8 , 49.93, 50.7 , 49.77, 51.5 , 48.6 , 49.07,
       47.53, 50.07, 52.43])

In [22]:
rainfall = np.random.randint(0,10,size=(12,30))
rainfall

array([[6, 1, 6, 2, 2, 3, 0, 0, 3, 5, 9, 3, 3, 3, 2, 6, 2, 6, 8, 6, 9, 6,
        0, 1, 0, 0, 3, 6, 7, 0],
       [3, 7, 4, 5, 8, 0, 8, 2, 7, 8, 4, 4, 6, 5, 4, 5, 0, 8, 9, 9, 2, 3,
        8, 3, 9, 7, 1, 0, 5, 4],
       [0, 5, 1, 6, 7, 7, 2, 5, 8, 5, 9, 7, 6, 6, 5, 6, 0, 3, 4, 6, 3, 8,
        1, 4, 9, 0, 4, 7, 0, 3],
       [4, 5, 2, 1, 3, 3, 4, 3, 7, 9, 1, 6, 1, 8, 1, 0, 9, 4, 2, 0, 8, 9,
        1, 6, 9, 2, 9, 6, 3, 7],
       [5, 0, 1, 4, 7, 1, 5, 0, 0, 7, 1, 7, 4, 9, 8, 4, 2, 1, 3, 2, 8, 3,
        3, 2, 9, 2, 6, 2, 3, 2],
       [2, 9, 4, 2, 4, 9, 5, 9, 1, 0, 7, 6, 1, 8, 7, 2, 9, 8, 5, 5, 0, 7,
        9, 8, 1, 3, 3, 7, 0, 1],
       [7, 3, 7, 3, 1, 4, 2, 0, 0, 2, 0, 5, 4, 7, 1, 9, 6, 1, 8, 3, 4, 2,
        6, 4, 3, 5, 4, 9, 9, 9],
       [6, 6, 5, 6, 2, 1, 8, 8, 1, 2, 1, 9, 7, 0, 7, 7, 2, 3, 0, 0, 0, 3,
        0, 8, 9, 8, 6, 4, 3, 1],
       [9, 1, 5, 0, 8, 1, 9, 7, 7, 6, 1, 8, 6, 8, 8, 6, 8, 6, 4, 2, 6, 6,
        6, 4, 7, 1, 4, 2, 1, 0],
       [1, 3, 9, 6, 3, 9, 4, 7, 7, 7,

In [23]:
rain_avg = np.round(np.mean(rainfall,axis=1),2)
rain_avg

array([3.6 , 4.93, 4.57, 4.43, 3.7 , 4.73, 4.27, 4.1 , 4.9 , 4.83, 5.1 ,
       4.87])

In [24]:
print('Average Temperature per month: ')
print(temp_avg)
print()
print('Average Humidity per month: ')
print(hum_avg)
print()
print('Average Rainfall per month: ')
print(rain_avg)
print()

Average Temperature per month: 
[36.17 36.8  36.2  36.17 35.6  36.07 37.5  37.3  36.53 37.97 37.97 37.57]

Average Humidity per month: 
[49.37 50.17 48.8  49.93 50.7  49.77 51.5  48.6  49.07 47.53 50.07 52.43]

Average Rainfall per month: 
[3.6  4.93 4.57 4.43 3.7  4.73 4.27 4.1  4.9  4.83 5.1  4.87]

