Create a NumPy array with values ranging from 0 to 10.

In [2]:
import numpy as np

arr = np.arange(11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


Create a NumPy array of zeros with shape (3, 4).

In [3]:
zeros_array = np.zeros((2, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create a NumPy array of ones with shape (2, 3, 4).

In [4]:
ones_arr = np.ones((2, 3, 4))
print(ones_arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Create a 3x3 identity matrix using NumPy.

In [4]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 2D NumPy array with shape (3, 3) and fill it with random values.

In [7]:
arr = np.random.rand(2, 3)
print(arr)

[[0.26464146 0.48810171 0.89678443]
 [0.28138007 0.85679191 0.92180135]]


Create a NumPy array with values from 1 to 10 and return only the even values.

In [6]:
# create NumPy array with values from 1 to 10
arr = np.arange(1, 11)

# return only the even values
even_arr = arr[arr % 2 == 0]

print(even_arr) 

[ 2  4  6  8 10]


Create a NumPy array with values from 1 to 20 and reshape it to (5, 4)

In [7]:
arr = np.arange(1, 21)

# reshape the array to a 5x4 matrix
arr_2d = arr.reshape(5, 4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


Transpose the array.

In [8]:
arr_t = arr_2d.transpose()
print(arr_t)


[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


Given two NumPy arrays, add them together element-wise.

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)

[5 7 9]


In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = a + b

print(result)

[[ 6  8]
 [10 12]]


Given a NumPy array, find the minimum and maximum values.

In [13]:
arr = np.array([5, 2, 8, 1, 6, 9, 3, 7, 4])

min_val = np.min(arr)
max_val = np.max(arr)
cumulative_sum = np.cumsum(arr)
cumulative_product = np.cumprod(arr)
std_dev = np.std(arr)
variance = np.var(arr)
mean = np.mean(arr)
median = np.median(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std_dev)
print("Variance:", variance)
print("Cumulative sum:", cumulative_sum)
print("Cumulative product:", cumulative_product)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
Variance: 6.666666666666667
Cumulative sum: [ 5  7 15 16 22 31 34 41 45]
Cumulative product: [     5     10     80     80    480   4320  12960  90720 362880]
Minimum value: 1
Maximum value: 9


A company has collected data on the number of orders they receive every hour for a week. They have stored this data in a NumPy array with shape (7, 24). Each row represents a day of the week, and each column represents an hour of the day. The company wants to analyze this data to identify the busiest day and hour of the week.

Question: Using NumPy, how would you identify the busiest day and hour of the week based on the data provided in the NumPy array?

In [5]:
import numpy as np

# Generate the NumPy array with shape (7, 24)
orders = np.random.randint(0, 100, size=(7, 24))

# Compute the sum of all elements of the NumPy array
total_orders = np.sum(orders)

# Compute the sum of each row of the NumPy array
daily_orders = np.sum(orders, axis=1)

# Compute the sum of each column of the NumPy array
hourly_orders = np.sum(orders, axis=0)

# Identify the busiest hour of the week
busiest_hour = np.argmax(hourly_orders)

# Identify the busiest day of the week
busiest_day = np.argmax(daily_orders)

print(f"The busiest hour of the week is {busiest_hour}:00, with {hourly_orders[busiest_hour]} orders received.")
print(f"The busiest day of the week is day {busiest_day+1}, with {daily_orders[busiest_day]} orders received.")


The busiest hour of the week is 10:00, with 473 orders received.
The busiest day of the week is day 1, with 1342 orders received.


A sports analyst wants to analyze the performance of a soccer team over a season. They have data on the number of goals scored and conceded in each match of the season, stored in two separate NumPy arrays. They also have data on the result of each match, stored in a separate NumPy array where 0 represents a loss, 1 represents a draw, and 3 represents a win.

Question: Using NumPy, how would you calculate the total number of goals scored and conceded by the team over the season, as well as their win percentage?

In [16]:
import numpy as np

# Data on number of goals scored and conceded in each match
goals_scored = np.array([2, 1, 3, 1, 0, 2])
goals_conceded = np.array([0, 1, 1, 1, 2, 1])

# Data on result of each match
result = np.array([3, 3, 3, 0, 0, 3])

# Calculate total number of goals scored and conceded
total_goals_scored = np.sum(goals_scored)
total_goals_conceded = np.sum(goals_conceded)

# Calculate number of wins, losses, and draws
num_wins = np.count_nonzero(result == 3)
num_losses = np.count_nonzero(result == 0)
num_draws = np.count_nonzero(result == 1)

# Calculate win percentage
total_matches = num_wins + num_losses + num_draws
win_percentage = num_wins / total_matches

print("Total goals scored:", total_goals_scored)
print("Total goals conceded:", total_goals_conceded)
print("Win percentage:", win_percentage)


Total goals scored: 9
Total goals conceded: 6
Win percentage: 0.6666666666666666


A company wants to analyze the sales data for their products over a year. They have data on the sales revenue, cost of goods sold (COGS), marketing expenses, and employee salaries for each product in each quarter of the year. The data is stored in a NumPy array with shape (4, 3, 5, 4), where the first dimension represents the quarter, the second dimension represents the product, the third dimension represents the attribute (revenue, COGS, marketing expenses, employee salaries), and the fourth dimension represents the month.

Question: Using NumPy, how would you calculate the following metrics for each quarter:

Gross profit margin (revenue - COGS) / revenue
Marketing spend as a percentage of revenue (marketing expenses / revenue)
Employee salary as a percentage of revenue (employee salaries / revenue)
Total revenue, COGS, marketing expenses, and employee salaries

In [20]:
import numpy as np

# Create a random sales data array
sales_data = np.random.randint(100, 1000, size=(4, 3, 5, 4))

# Calculate the metrics for each quarter
for i in range(4):
    print(f"Metrics for Quarter {i+1}:")
    quarter_data = sales_data[i]
    revenue = quarter_data[:, 0, :].sum()
    cogs = quarter_data[:,  1, :].sum()
    marketing_expenses = quarter_data[:, 2, :].sum()
    employee_salaries = quarter_data[:, 3, :].sum()
    gross_profit_margin = (revenue - cogs) / revenue
    marketing_spend_percent = marketing_expenses / revenue * 100
    employee_salary_percent = employee_salaries / revenue * 100
    print(f"Total revenue: {revenue}")
    print(f"Total COGS: {cogs}")
    print(f"Total marketing expenses: {marketing_expenses}")
    print(f"Total employee salaries: {employee_salaries}")
    print(f"Gross profit margin: {gross_profit_margin:.2%}")
    print(f"Marketing spend as a percentage of revenue: {marketing_spend_percent:.2%}")
    print(f"Employee salary as a percentage of revenue: {employee_salary_percent:.2%}")


Metrics for Quarter 1:
Total revenue: 7268
Total COGS: 6576
Total marketing expenses: 5230
Total employee salaries: 7617
Gross profit margin: 9.52%
Marketing spend as a percentage of revenue: 7195.93%
Employee salary as a percentage of revenue: 10480.19%
Metrics for Quarter 2:
Total revenue: 6937
Total COGS: 6512
Total marketing expenses: 6043
Total employee salaries: 7345
Gross profit margin: 6.13%
Marketing spend as a percentage of revenue: 8711.26%
Employee salary as a percentage of revenue: 10588.15%
Metrics for Quarter 3:
Total revenue: 7032
Total COGS: 6787
Total marketing expenses: 7461
Total employee salaries: 7240
Gross profit margin: 3.48%
Marketing spend as a percentage of revenue: 10610.07%
Employee salary as a percentage of revenue: 10295.79%
Metrics for Quarter 4:
Total revenue: 7298
Total COGS: 7578
Total marketing expenses: 7446
Total employee salaries: 5724
Gross profit margin: -3.84%
Marketing spend as a percentage of revenue: 10202.80%
Employee salary as a percentage

In [21]:
# Generate random sales data
sales_data = np.random.randint(100, 1000, size=(4, 3, 5, 4))

In [23]:
# Get the total revenue for the first product in each quarter
total_revenue = sales_data[:, 0, 0, :].sum()
print(total_revenue)

8451


In [24]:
sales_data = np.random.randint(100, 1000, size=(4, 3, 5))

In [25]:
sales_data

array([[[725, 832, 835, 283, 995],
        [348, 141, 125, 623, 332],
        [947, 941, 518, 293, 969]],

       [[928, 248, 266, 999, 757],
        [234, 194, 732, 307, 576],
        [371, 539, 592, 822, 822]],

       [[572, 149, 737, 773, 692],
        [914, 144, 186, 731, 374],
        [787, 396, 810, 260, 754]],

       [[829, 604, 468, 643, 878],
        [748, 459, 544, 997, 637],
        [385, 554, 295, 117, 556]]])

array[start1:end1, start2:end2, start3:end3]


where start1:end1 specifies the range of indices to include along the first dimension, start2:end2 specifies the range of indices to include along the second dimension, and start3:end3 specifies the range of indices to include along the third dimension.

For example, suppose you have a 3D array named sales_data with shape (4, 3, 5), and you want to extract a subset of data for the first quarter, second product, and all months. You would use the following slicing notation:

In [26]:
subset = sales_data[0, 1, :]


In [27]:
subset

array([348, 141, 125, 623, 332])

In [28]:
subset = sales_data[0, :, :2]


In [29]:
subset

array([[725, 832],
       [348, 141],
       [947, 941]])

In [10]:
import numpy as np
taaha=np.ones((1,2,3))
print(taaha)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
row=np.sum(taaha,axis=1)
print(row)

[[2. 2. 2.]]
