In [1]:
import numpy as np

In [47]:
year = np.random.randint(1000,10000,size = (4,4,4))
print(year)

[[[8502 7933 8400 1101]
  [9038 3316 7427 5462]
  [9915 6197 3298 7247]
  [9564 5671 9359 4651]]

 [[5297 5971 1729 6513]
  [4708 8404 8838 3042]
  [5513 8136 7617 3786]
  [8206 8052 2334 8197]]

 [[9315 8652 7847 2241]
  [3592 3152 7170 2281]
  [1499 5385 5402 2605]
  [4358 5812 9836 5855]]

 [[6041 6673 7762 8086]
  [5682 4960 6748 1636]
  [9619 1893 6676 5503]
  [9846 7476 3822 2811]]]


In [48]:
sum = 0
sum = year.sum(axis=0,dtype=float)

In [49]:
for i in range(4):
    for j in range(4):
         print(f'Year : {i+1} Quarter : {j+1} {sum[i][j]}')

Year : 1 Quarter : 1 29155.0
Year : 1 Quarter : 2 29229.0
Year : 1 Quarter : 3 25738.0
Year : 1 Quarter : 4 17941.0
Year : 2 Quarter : 1 23020.0
Year : 2 Quarter : 2 19832.0
Year : 2 Quarter : 3 30183.0
Year : 2 Quarter : 4 12421.0
Year : 3 Quarter : 1 26546.0
Year : 3 Quarter : 2 21611.0
Year : 3 Quarter : 3 22993.0
Year : 3 Quarter : 4 19141.0
Year : 4 Quarter : 1 31974.0
Year : 4 Quarter : 2 27011.0
Year : 4 Quarter : 3 25351.0
Year : 4 Quarter : 4 21514.0
