In [1]:
import numpy as np

In [2]:
random_arr = np.random.rand(5,5)
random_arr

array([[0.72693302, 0.51237737, 0.53838226, 0.7355256 , 0.99444997],
       [0.42104262, 0.41116589, 0.4328038 , 0.58035214, 0.04341136],
       [0.03616049, 0.22006987, 0.15863897, 0.18002087, 0.34447543],
       [0.81579915, 0.30003633, 0.69527514, 0.92839645, 0.79492916],
       [0.03315272, 0.54039617, 0.08386075, 0.95923496, 0.53792291]])

In [33]:
np.partition(random_arr.flatten(), 1)[1]

0.036160488698877

In [6]:
max_num = np.max(random_arr)
max_num

0.9944499693212997

In [11]:
print('Random array: ')
print(random_arr)
print()
print(f'Second Minimum : {second_min}')
print()
print(f'Maximum Number : {max_num}')

Random array: 
[[0.72693302 0.51237737 0.53838226 0.7355256  0.99444997]
 [0.42104262 0.41116589 0.4328038  0.58035214 0.04341136]
 [0.03616049 0.22006987 0.15863897 0.18002087 0.34447543]
 [0.81579915 0.30003633 0.69527514 0.92839645 0.79492916]
 [0.03315272 0.54039617 0.08386075 0.95923496 0.53792291]]

Second Minimum : 0.036160488698877

Maximum Number : 0.9944499693212997


### Part (b) -> Normalization

In [17]:
normalized_arr = random_arr/max_num
normalized_arr

array([[0.73099003, 0.51523695, 0.54138697, 0.73963057, 1.        ],
       [0.42339246, 0.4134606 , 0.43521928, 0.58359109, 0.04365364],
       [0.0363623 , 0.22129808, 0.15952434, 0.18102556, 0.34639795],
       [0.82035213, 0.30171083, 0.69915547, 0.93357784, 0.79936567],
       [0.03333775, 0.54341212, 0.08432877, 0.96458846, 0.54092506]])

In [19]:
mean_of_arr = np.mean(random_arr)
mean_of_arr

0.4809925359311201

In [22]:
random_arr[random_arr==0] = mean_of_arr
print(f'Array after removing 0\'s: ')
print(random_arr)

Array after removing 0's: 
[[0.72693302 0.51237737 0.53838226 0.7355256  0.99444997]
 [0.42104262 0.41116589 0.4328038  0.58035214 0.04341136]
 [0.03616049 0.22006987 0.15863897 0.18002087 0.34447543]
 [0.81579915 0.30003633 0.69527514 0.92839645 0.79492916]
 [0.03315272 0.54039617 0.08386075 0.95923496 0.53792291]]


## Question 2